イベント開催会社を「株式会社インプレス」に更新
katsu84/ichiyasaGitSample pull request #1
Opened 2021-04-28 07:46 UTC by katsu84

### 変更内容
イベント開催会社を「株式会社インプレス」に更新しました。

### 背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2021-04-28 13:32 UTC, katsu84mt commented
修正ありがとうございます！。問題ないのでマージします。

2021-04-28 13:44 UTC, katsu84mt commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
「新株式会社インプレス」と正式な表記でお願いします。

2021-04-28 13:49 UTC, katsu84mt requested changes
修正ありがとうございます。指摘の確認と修正をお願いします。

2021-04-28 13:49 UTC, katsu84mt commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
「新株式会社インプレス」と正式な表記でお願いします。

2021-04-29 13:33 UTC, katsu84 commented
新インプレスに更新　修正

2021-04-29 13:35 UTC, katsu84 commented
新リクエストに修正更新しました。

2021-04-29 13:35 UTC, closed without merging

2021-04-29 13:45 UTC, katsu84mt reviewed
ありがとうございます

2021-04-29 13:52 UTC, katsu84 commented
yorosiku

2021-04-29 13:53 UTC, katsu84mt reviewed
OK

2021-04-29 13:58 UTC, katsu84mt commented
ありがとう